# Generated by Django 5.0.4 on 2024-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="food",
            name="total_weight",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orders",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orders",
            name="service_fee",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
