# Generated by Django 5.0.4 on 2024-05-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0003_rename_chargingstations_chargingstation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="delivery_address",
        ),
        migrations.CreateModel(
            name="Customer_delivery",
            fields=[
                ("delivery_id", models.AutoField(primary_key=True, serialize=False)),
                ("delivery_address", models.CharField(max_length=255)),
                ("delivery_city", models.CharField(max_length=255)),
                ("delivery_state", models.CharField(max_length=255)),
                ("delivery_postcode", models.IntegerField()),
                ("delivery_phone", models.CharField(max_length=255)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="droneapp.customer",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Payment",
            new_name="Paymentmethod",
        ),
        migrations.CreateModel(
            name="Order_General",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "delivery_status",
                    models.CharField(default="Not Finished", max_length=255),
                ),
                ("order_placed", models.BooleanField(default=True)),
                ("order_packed", models.BooleanField(default=False)),
                ("order_shipped", models.BooleanField(default=False)),
                (
                    "service_fee",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
                ),
                ("total_price", models.IntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="droneapp.customer",
                    ),
                ),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="droneapp.drone",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="droneapp.paymentmethod",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="droneapp.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_Food",
            fields=[
                ("order_food", models.AutoField(primary_key=True, serialize=False)),
                ("quatity", models.IntegerField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="droneapp.food",
                    ),
                ),
                (
                    "order_generalid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="droneapp.order_general",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
