# Generated by Django 5.0.4 on 2024-05-15 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0004_customuser_restaurantuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurantuser",
            name="email",
        ),
    ]
