# Generated by Django 5.0.4 on 2024-05-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "droneapp",
            "0004_remove_customer_delivery_address_customer_delivery_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(default="Melbourne", max_length=255),
        ),
    ]
