# Generated by Django 5.0.4 on 2024-05-16 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0005_customer_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order_general",
            name="restaurant",
        ),
        migrations.AddField(
            model_name="order_food",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="droneapp.restaurant",
            ),
        ),
    ]
