# Generated by Django 5.0.4 on 2024-05-17 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0006_restaurantuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer_delivery",
            fields=[
                ("delivery_id", models.AutoField(primary_key=True, serialize=False)),
                ("delivery_address", models.CharField(max_length=255)),
                ("delivery_city", models.CharField(max_length=255)),
                ("delivery_state", models.CharField(max_length=255)),
                ("delivery_postcode", models.IntegerField()),
                ("delivery_phone", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Order_Food",
            fields=[
                ("order_food", models.AutoField(primary_key=True, serialize=False)),
                ("food", models.CharField(max_length=255)),
                ("quatity", models.IntegerField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="droneapp.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_General",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "delivery_status",
                    models.CharField(default="Not Finished", max_length=255),
                ),
                ("order_placed", models.BooleanField(default=True)),
                ("order_packed", models.BooleanField(default=False)),
                ("order_shipped", models.BooleanField(default=False)),
                (
                    "service_fee",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
                ),
                ("total_price", models.IntegerField(default=0)),
                ("street", models.CharField(default="123 street", max_length=255)),
                ("zip_code", models.IntegerField(default=3000)),
                ("city", models.CharField(default="Melbourne", max_length=255)),
                ("province", models.CharField(default="VIC", max_length=255)),
                ("phone", models.CharField(default="1234567890", max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="drone",
            name="current_load",
        ),
        migrations.RemoveField(
            model_name="drone",
            name="station_id",
        ),
        migrations.RemoveField(
            model_name="restaurantuser",
            name="business_type",
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(default="Melbourne", max_length=255),
        ),
        migrations.AddField(
            model_name="customer_delivery",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="droneapp.customer"
            ),
        ),
        migrations.RenameModel(
            old_name="Payment",
            new_name="Paymentmethod",
        ),
        migrations.AddField(
            model_name="order_general",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="droneapp.customer"
            ),
        ),
        migrations.AddField(
            model_name="order_general",
            name="drone",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="droneapp.drone",
            ),
        ),
        migrations.AddField(
            model_name="order_general",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="droneapp.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="order_food",
            name="order_generalid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="droneapp.order_general",
            ),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
