# Generated by Django 5.0.4 on 2024-05-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0006_remove_order_general_restaurant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_general",
            name="city",
            field=models.CharField(default="Melbourne", max_length=255),
        ),
        migrations.AddField(
            model_name="order_general",
            name="phone",
            field=models.CharField(default="1234567890", max_length=255),
        ),
        migrations.AddField(
            model_name="order_general",
            name="province",
            field=models.CharField(default="VIC", max_length=255),
        ),
        migrations.AddField(
            model_name="order_general",
            name="street",
            field=models.CharField(default="123 street", max_length=255),
        ),
        migrations.AddField(
            model_name="order_general",
            name="zip_code",
            field=models.IntegerField(default=3000),
        ),
    ]
