# Generated by Django 5.0.4 on 2024-05-17 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0007_customer_delivery_order_food_order_general_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant_Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New order", "New order"),
                            ("Preparing", "Preparing"),
                            ("Ready", "Ready"),
                            ("Delivering", "Delivering"),
                            ("Delivered", "Delivered"),
                        ],
                        default="New order",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="droneapp.order_general",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="droneapp.restaurant",
                    ),
                ),
            ],
        ),
    ]
