# Generated by Django 5.0.4 on 2024-05-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0008_restaurant_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RestaurantUser",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="email",
            field=models.EmailField(default="abc@gmail.com", max_length=254),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="password",
            field=models.CharField(default="123456", max_length=255),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(default="1234567890", max_length=15),
        ),
    ]
