# Generated by Django 5.0.4 on 2024-05-16 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0008_alter_order_general_drone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drone",
            name="station_id",
        ),
        migrations.AddField(
            model_name="drone",
            name="station",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="droneapp.chargingstation",
            ),
        ),
    ]
