# Generated by Django 5.0.4 on 2024-05-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0010_remove_drone_current_load_remove_drone_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_food",
            name="food",
            field=models.CharField(max_length=255),
        ),
    ]
