# Generated by Django 5.0.4 on 2024-05-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0010_remove_restaurant_opening_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant_order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New order", "New order"),
                    ("Preparing", "Preparing"),
                    ("Ready", "Ready"),
                    ("Delivering", "Delivering"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="New order",
                max_length=255,
            ),
        ),
    ]
