# Generated by Django 5.0.4 on 2024-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0011_alter_restaurant_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_general",
            name="time_ordered",
            field=models.CharField(default="00:00:00", max_length=255),
        ),
        migrations.AddField(
            model_name="restaurant_order",
            name="pickup_time",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
