# Generated by Django 5.0.4 on 2024-05-17 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0011_alter_order_food_food"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order_food",
            old_name="quatity",
            new_name="quantity",
        ),
    ]
