# Generated by Django 5.0.4 on 2024-05-17 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0012_order_general_time_ordered_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order_food",
            old_name="quatity",
            new_name="quantity",
        ),
    ]
