# Generated by Django 5.0.4 on 2024-05-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0013_rename_quatity_order_food_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_food",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
