# Generated by Django 5.0.4 on 2024-05-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0014_restaurant_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_general",
            name="time_ordered",
            field=models.CharField(default="00:00:00", max_length=255),
        ),
    ]
