# Generated by Django 5.0.4 on 2024-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0014_order_food_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant_order",
            name="pickup_time",
        ),
        migrations.AddField(
            model_name="order_general",
            name="pickup_time",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
