# Generated by Django 5.0.4 on 2024-05-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0015_order_general_time_ordered"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant_order",
            name="pickup_time",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
