# Generated by Django 5.0.4 on 2024-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0015_remove_restaurant_order_pickup_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_general",
            name="total_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
