# Generated by Django 5.0.4 on 2024-05-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0016_order_general_total_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_general",
            name="status",
            field=models.CharField(
                choices=[
                    ("New order", "New order"),
                    ("Preparing", "Preparing"),
                    ("Ready", "Ready"),
                    ("Delivering", "Delivering"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="New order",
                max_length=255,
            ),
        ),
    ]
