# Generated by Django 5.0.4 on 2024-05-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0016_restaurant_order_pickup_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="opening_hours",
        ),
        migrations.RemoveField(
            model_name="restaurant_order",
            name="pickup_time",
        ),
        migrations.AddField(
            model_name="order_general",
            name="pickup_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AddField(
            model_name="order_general",
            name="status",
            field=models.CharField(
                choices=[
                    ("New order", "New order"),
                    ("Preparing", "Preparing"),
                    ("Ready", "Ready"),
                    ("Delivering", "Delivering"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="New order",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="order_general",
            name="total_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="closing_time",
            field=models.TimeField(default="23:59:59"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="email",
            field=models.EmailField(default="abc@gmail.com", max_length=254),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="opening_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="password",
            field=models.CharField(default="123456", max_length=255),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(default="1234567890", max_length=15),
        ),
    ]
