# Generated by Django 5.0.4 on 2024-05-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0017_remove_restaurant_opening_hours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="picture_link",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
    ]
