# Generated by Django 5.0.4 on 2024-05-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0018_remove_restaurant_picture_link_restaurant_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="icon",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="picture_link",
            field=models.CharField(default="123", max_length=255),
        ),
    ]
