# Generated by Django 5.0.4 on 2024-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("droneapp", "0019_remove_restaurant_icon_restaurant_picture_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_food",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
